FROM python:3.8-slim-buster

RUN mkdir ./app
COPY . /app
WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    python3-dev \
    libffi-dev \
    libssl-dev \
    && apt-get clean

RUN pip install -r /app/requirements_dev.txt

CMD [ "python3" ,"app.py" ]