stages:
  training:
    cmd: python src/pipeline/training_pipeline.py
    deps:
      - src/components/data_ingestion.py
      - src/components/data_transformation.py
      - src/components/model_evaluation.py
      - src/components/model_trainer.py
    outs:
      - artifacts/raw.csv
      - artifacts/train.csv
      - artifacts/test.csv
      - artifacts/preprocess.pkl
      - artifacts/model.pkl
